### ISSUE TITLE
Media Feature - Support Compression and EXIF data

### ISSUE THREAD

**Issue by dhaligas** [jamesmontemagno/Xamarin.Plugins#126] opened 2015-11-05 16:22 UTC
Support Compression and EXIF data

I would like to see an option to add compression option and get full EXIF data back from the photos.

**Comment by jamesmontemagno** [comment] 2015-11-07 07:30
Duplicate of https://github.com/jamesmontemagno/Xamarin.Plugins/issues/76

**Closed by jamesmontemagno** 2015-11-07 07:30 UTC
