### ISSUE TITLE
ConnectivityChanged not fired when switching between cellular and wifi

### ISSUE THREAD

**Issue by dcasbonne** [jamesmontemagno/Xamarin.Plugins#280] opened 2016-04-15 02:10 UTC
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [ x] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ x] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [ ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: 2.1.2
Device Tested On: Nexus 5 Android 6.0.1
Simulator Tested On: (no cellular connection possible on simulators)

### Expected Behavior

You said that this event is fired when connectivity is gained, changed or loosed.
When switching between cellular and wifi connection, this event should be fired and the event args could eventually contains the ConnectionTypes added or removed.

### Actual Behavior

Event is only fired when connectivity is gained or loosed. 

### Steps to reproduce the Behavior

Deploy a test application to a real device without any connection.
Activate cellular connection => event fired
Activate wifi connection => event not fired (but if we check the ConnectionTypes, Cellular has been replaced by Wifi)
Desactivate wifi connection => event not fired (but if we check the ConnectionTypes Wifi has been replaced by Cellular)
Desactivate cellular connection => event fired

Thanks in advance ;)

**Comment by Tviljan** [comment] 2016-06-14 05:58
Any workarounds for this?

**Comment by jamesmontemagno** [comment] 2016-06-29 04:35
Duplicate of: https://github.com/jamesmontemagno/ConnectivityPlugin/issues/3

**Closed by jamesmontemagno** 2016-06-29 04:35 UTC
Labels: Connectivity
