### ISSUE TITLE
CrossConnectivity.Current.IsRemoteReachable returns false when debugger attached

### ISSUE THREAD

**Issue by PenaPP** [jamesmontemagno/Xamarin.Plugins#74] opened 2015-06-09 12:47 UTC
IsRemoteReachable returns false in Windows Store application when run from Visual Studio in Debug mode (even though IsConnected is true and web browser can connect the specified host). Closing the application and running it without the debugger works, but I can't debug enything else then ;)

**Comment by jamesmontemagno** [comment] 2015-07-06 23:47
Which Url are you hitting?

**Comment by PenaPP** [comment] 2015-07-08 07:39
Well it seems that it affects just local network addresses. I call this...

    await CrossConnectivity.Current.IsRemoteReachable("192.168.10.223", 80, 2000)

and it always returns false when the debugger is attached.

**Comment by jamesmontemagno** [comment] 2015-07-23 02:08
Could be something strange with loopback and hitting an IP on the machine.

**Comment by PenaPP** [comment] 2015-07-26 18:46
jamesmontemagno: Are you able to reproduce the problem too or is it just my local problem? :)

**Comment by jamesmontemagno** [comment] 2015-12-03 22:46
I am not able to reproduce this at all and havent' seen this. closing unless it pops up. hitting an IP is not suggested.

**Closed by jamesmontemagno** 2015-12-03 22:46 UTC
Labels: bug, Connectivity
