### ISSUE TITLE
[BUG] Media - Images lose basic metadata (iOS)

### ISSUE THREAD

**Issue by LostBalloon1** [jamesmontemagno/Xamarin.Plugins#82] opened 2015-07-03 14:55 UTC
Image files contain basic metadata about the image. Exif and other information is lost when processed by the picker.

Bug can reproduced by extracting an image from the camera roll and the same image from the app after it has been processed by the picker. Both images then inspected using the preview app on the mac show a significant loss of metadata.

**Comment by systemiya** [comment] 2015-07-24 10:18
TakePhoto also only contains just "Orientation", "ColorSpace", "PixelXDimension" and "PixelYDimension"

**Comment by lodev09** [comment] 2015-11-01 13:58
@jamesmontemagno I heard that when you save the photo to the app's directory, it won't let you retain the metadata. Please if you can expose an option to save the photo to the user's album and retain meta data info? Also if you can include it to the `MediaFile` return.

Thanks!

**Comment by dhaligas** [comment] 2015-11-05 16:23
+1

**Comment by monostefan** [comment] 2015-11-19 15:18
Duplicate of #76?

**Comment by jamesmontemagno** [comment] 2015-12-03 22:42
Sooooo, I added a new flag to save to gallery:

https://github.com/jamesmontemagno/Xamarin.Plugins/issues/149

Is this good enough for everyone? Let me know.

**Comment by LostBalloon1** [comment] 2015-12-04 16:45
I really need the image, which ends up in my application's folders, to contain all the images metadata. The fact that a copy can be saved to the gallery doesn't serve the fact that the images our app work with lose every bit of metadata in their binary.

We should be able to extract those images from our app (upload, itunes (or other tool that allows to get the files)) and inspect them for their metadata (using preview or photos - on the mac as an example) and seeing that it is still there. That data needs to remain in the *.jpg or *.png If the data which is normally in the file is not in it at the end, the change does not solve my problem at all.

I understand that for metadata such as GeoLocation, apple does not add it to the image's metadata directly in the image binary for "security" reasons, I'm ok with it just exposed in whichever way and left up to us to be handled, but there really needs to be no loss of metadata in the binary file.

**Comment by lodev09** [comment] 2015-12-04 19:11
@jamesmontemagno thanks for fixing that but it turns the App I'm working on needs to really save an image to the App directory so I searched for other solutions and found this [PR](https://github.com/XLabs/Xamarin-Forms-Labs/pull/953) from XLabs. If you could incorporate this to your plugin, it would be awesome.

@LostBalloon1 see above, basically extracting metadata info and saving it to the `MediaFile` `JpegInfo` property from the source image before saving to app directory and just process the embedding somewhere else. You might need to tweak some things to accommodate your goals though.

Hope that helps. :)

**Comment by jamesmontemagno** [comment] 2015-12-04 19:12
I am closing this and re-opening as a new "bug" because there is a lot of confusion as to what needs to be done.

**Closed by jamesmontemagno** 2015-12-04 19:12 UTC
Labels: bug, enhancement, Media
