### ISSUE TITLE
[Feature Request] Media - obtaining metadata

### ISSUE THREAD

**Issue by LostBalloon1** [jamesmontemagno/Xamarin.Plugins#76] opened 2015-06-15 13:54 UTC
Hi,

As stated in the title, it would be nice if the MediaFile provided (or had the possibility to) metadata about the media in question.
For instance, on iOS geolocation information is stored for images and videos.

Geolocation is my primary concern, but I'm sure other interesting metadata could be exposed too.

I would simply post process in my project if it does not fit well into the library, though if I'm not mistaken, the picker in iOS provides the metadata when picking:

    (NSDictionary)e.Info [UIImagePickerController.MediaMetadata]

I would not mind adding it to the implementation myself if need be (and if you have any design preferences, I'm all ears)

**Comment by monostefan** [comment] 2015-10-01 14:23
Hi there!

I have investigated in this issue a little bit because we need to solve it in our app at least for photos as well. I was able to solve the issue when picking from the saved photos album but not when a picture is taken.

For picked images, the solutions is to load the data using Photokit. Within the image picker info dictionary, there's also a reference url which can be used to request the photo:

    var referenceUrl = (NSUrl)info[UIImagePickerController.ReferenceUrl];

    var asset = PHAsset.FetchAssets(new[] {referenceUrl}, null).firstObject as PHAsset;

    if (asset != null)
    {
        var imgMgr = new PHImageManager();
        imgMgr.RequestImageData(asset, new PHImageRequestOptions
            {
                Synchronous = true,
                NetworkAccessAllowed = true,
                ResizeMode = PHImageRequestOptionsResizeMode.None,
                DeliveryMode = PHImageRequestOptionsDeliveryMode.HighQualityFormat
            }, (data, uti, orientation, imgInfo) =>
            {
                using (FileStream fs = File.OpenWrite(path))
                using (Stream s = data.AsStream())
                {
                    s.CopyTo(fs);
                    fs.Flush();
                }
            });
    } 

However, when an image is taken, we do not get a referenceUrl, just the image and meta data. Unfortunately, it seems like only way to encode the received image as JPEG with EXIF metadata in the whole iOS Framework is to save the image to the saved photos album using ALAssetsLibrary:

    var library = new ALAssetsLibrary();

    library.WriteImageToSavedPhotosAlbum(image.CGImage, meta, (url, error) => {

        // Export image data using PhotoKit from here

    });

That could potentially work, but it would also mean that every image taken using the plugin will be saved in the photos album. This might seem like an acceptable side-effect for some, but it's a changing behavior nevertheless.

When I tried to go down that route, I got stuck however. While `WriteImageToSavedPhotosAlbum()` works fine in other scenarios for me, the callback never returned when used in the media plugin. I have absolutely no idea why.

My repository is here: https://github.com/monostefan/Xamarin.Plugins

Maybe anyone has an idea how to tackle this issue?

There must be a way to get images with metadata when using the Media Plugin!

**Comment by Jazzeroki** [comment] 2015-11-09 18:57
The reason we are losing Exif data on images in iOS is that the media picker is casting the image to a UIImage.  Whenever that happens iOS strips out all the Exif data.  A further complication of this issue there's a property that is supposed to contain the file path as part of this picker.  But the iOS picker only returns a path to a copy of the image that has already been cast as a UIImage and is in temporary storage.  

To get around this I had to include the original source into the project and used something like this to get the path to the original image that had the exif data.

private MediaFile GetPictureMediaFile(NSDictionary info)
		{
			var image = (UIImage)info[UIImagePickerController.EditedImage] ?? (UIImage)info[UIImagePickerController.OriginalImage];

			string path = GetOutputPath(MediaImplementation.TypeImage,
				              options.Directory ?? ((IsCaptured) ? String.Empty : "temp"),
				              options.Name);

			using (FileStream fs = File.OpenWrite(path))
			using (Stream s = new NSDataStream(image.AsJPEG()))
			{
				s.CopyTo(fs);
				fs.Flush();
			}

			Action<bool> dispose = null;
			if (this.source != UIImagePickerControllerSourceType.Camera)
				dispose = d => File.Delete(path);

			return new MediaFile(path, () => File.OpenRead(path), dispose: dispose)
			{
				OriginalPath = info[UIImagePickerController.ReferenceUrl].ToString()
			};
		}

**Comment by jamesmontemagno** [comment] 2015-12-03 22:42
Sooooo, I added a new flag to save to gallery:

https://github.com/jamesmontemagno/Xamarin.Plugins/issues/149

Is this good enough for everyone? Let me know.

**Comment by jamesmontemagno** [comment] 2015-12-04 19:11
I am closing this as it is very confusing with all the comments as to what the issue is. Please add notes for abstracting information from the metadate/exif to https://github.com/jamesmontemagno/Xamarin.Plugins/issues/155

**Closed by jamesmontemagno** 2015-12-04 19:11 UTC
Labels: enhancement, Media

**Comment by Axel3232** [comment] 2015-12-09 12:35
See my PR https://github.com/XLabs/Xamarin-Forms-Labs/pull/953
