### ISSUE TITLE
Expression of type 'System.Collections.Generic.IEnumerable`1[Plugin.Contacts.Abstractions.Contact]' cannot be used for return type 'System.Linq.IQueryable`1[Plugin.Contacts.Abstractions.Contact]' when i am using contacts pluggin

### ISSUE THREAD

**Issue by sateeshtec** [jamesmontemagno/Xamarin.Plugins#278] opened 2016-04-14 05:41 UTC
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [ ] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [ ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin:
Device Tested On:
Simulator Tested On:

### Steps to reproduce the Behavior

**Comment by jamesmontemagno** [comment] 2016-04-14 17:58
Can you show me the query you are using?

**Comment by jamesmontemagno** [comment] 2016-04-14 17:58
Duplicate of: https://github.com/jamesmontemagno/Xamarin.Plugins/issues/272

**Closed by jamesmontemagno** 2016-04-14 17:58 UTC
